#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
if [ $# -lt 4 ]; then

    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_Bash script that transfers a file from our client to a server"
    exit 1
fi
# Assign parameters to varables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Disable strictly host key checking for scp
export SCP_OPTIONS="-o StrictHostKeyChecking=no"

# Transfer the file using scp
scp -i "$PATH_TO_SSH_KEY" "$SCP_OPTIONS" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
if [ $? -eq 0 ]; then
    echo "File transferred successfully!"
else
    echo "Error occurred while transferring the file."
fi
