#!/usr/bin/env bash
# Installing Ngnx on our web-01 server
# Update packages list
sudo apt update
# Install Nignx
sudo apt -y install nginx
ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www/html

sudo chmod -R 755 /var/www

# creating the text for my page
echo "Hello World!" > /var/www/html/hello.html
NGINX_CONFIG="
server {
    listen 80;
    listen [::]:80;

    root /var/www/html;
    index hello.html index.htm index.nginx-debian.html;

    server_name localhost;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
"
echo "$NGINX_CONFIG" | sudo tee /etc/nginx/sites-enabled/default > /dev/null

# Restart Nginx
sudo service nginx restart
echo "Congratulation Nginx has been install successfully. you can try it out with 'curl localhost'"

