#!/usr/bin/env bash
# Installing Nignx on our web-01 server
# Update packages list
sudo apt update
# Install Nignx
sudo apt -y install nginx
ufw allow 'Nignx HTTP'
sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
