#!/usr/bin/env bash

# Update packages
sudo apt update

# Install nginx
sudo apt-get -y install nginx

# Start up nginx
sudo service nginx start

# Allow firewall
sudo ufw allow 'Nginx HTTP'

# Make the necessary directories
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# NGINX configuration
NGINX_CONFIG="
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location ~ ^/redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
"

# Write NGINX configuration to the default site
echo "$NGINX_CONFIG" | sudo tee /etc/nginx/sites-enabled/default > /dev/null

# Restart NGINX
sudo service nginx restart

echo "NGINX has been installed and configured. You can test it with 'curl localhost'"
