#!/usr/bin/env bash

# Install nginx on a new ubuntu page and design a custom 404 page

# Install Nginx
sudo apt -y install nginx
ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# creating the text for my page
echo "I love programming" > /var/www/html/redirect_me.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Create a new Nginx configuration snippet for redirection
REDIRECT_CONFIG="
server {
    listen 80;
    listen [::]:80;

    root /var/www/html;
    index redirect_me.html index.html index.nginx-debian.html;

    server_name localhost;

    location /redirect_me {
    rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
}
        error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}
"
echo "$REDIRECT_CONFIG" | sudo tee /etc/nginx/sites-enabled/default > /dev/null

# Restart Nginx
sudo service nginx restart

echo "Congratulation Nginx has been installed and configured successfully. You can test the redirection with 'curl localhost/redirect_me'"
