#!/usr/bin/env bash
# A script that generate a mysql dump and create a compressd archive
if [ $# -ne 1 ];then
    echo "USAGE: $0 <MYSQL_root_password>"
    exit 1
fi

TIMESTAMP=$(date +"%d-%m-%Y")

MYSQL_ROOT_PASSWORD="$1"
sudo mysqldump -u root -p"$MYSQL_ROOT_PASSWORD" --all-databases | sudo tee backup.sql
tar -czf "$TIMESTAMP.tar.gz"  backup.sql
echo "Backup archive created: $BACKUP_DIR/$TIMESTAMP.tar.gz"
