#!/usr/bin/env bash
# A script that generate a mysql dump and create a compressd archive
if [ $# -ne 1 ];then
    echo "USAGE: $0 <MYSQL_root_password>"
    exit 1
fi
BACKUP_DIR="HOME"
TIMESTAMP=$(date +"%d-%m-%Y")

MYSQL_ROOT_PASSWORD="$1"
mysqldump -u root -p"$MYSQL_ROOT_PASSWORD" --all-database > "$BACKUP_DIR/backup.sql"
tar -czf "$BACKUP_DIR/$TIMESTAMP.tar.gz" -C "$BACKUP_DIR" backup.sql
echo "Backup archive created: $BACKUP_DIR/$TIMESTAMP.tar.gz"
