#!/usr/bin/env bash
#Display "Best School and display bad luck for 4 iteration so on
count=0
while [ "$count" -lt 10 ]
do
    if [ $count -eq 3 ]
    then
	echo "bad luck"
    elif [ $count -eq 7 ]
    then
	
	echo "good luck"

    else
	echo "Best School"
    fi
    ((count++))
done
