#!/usr/bin/env bash
#Disspy numbers from 1 to 20 with a while loop
count=1
while [ "$count" -lt 21 ]
do
    if [ $count -eq 5 ]
    then
	echo "bad luck from China"
    elif [ $count -eq 10 ]
    then
	echo "bad luck from Japan"
    elif [ $count -eq 18 ]
    then
	echo "bad luck from Italy"
    else
	echo "$count"
    fi
    ((count++))
done
