#!/usr/bin/env bash
#configure an ubuntu server with the followin ip address
# -  localhost resolve to 127.0.0.2
# -  facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
