#!/usr/bin/env bash
# configures ngix to server our page in it's public ip and local ip

server {
       listen 80;
       server_name codezenith.tech 127.0.0.1;

       location / {
       include proxy_params;
       proxy_pass http://0.0.0.0:5000;
       }

}
