#!/usr/bin/env bash
# configures ngix to server our page in it's public ip and local ip
server "{
    listen 80;
    server_name 100.26.20.18 127.0.0.1;

    location /airbnb-onepage/ {
        include proxy_params;
        proxy_pass http://0.0.0.0:5000;
    }

}
"
