#!/usr/bin/env bash
#configure an nginx proxy to server handle traffic and route to there port
server "{
    listen 80;
    server_name 100.26.20.18 127.0.0.1;

    location /airbnb-onepage/ {
        include proxy_params;
        proxy_pass http://0.0.0.0:5000;
    }

    location /airbnb-dynamic/number_odd_or_even/ {
        include proxy_params;
        proxy_pass http://0.0.0.0:5001;
    }

}
"
